#set -g default-command "reattach-to-user-namespace -l /bin/zsh"
setw -g automatic-rename off
#setw -g utf8 on
setw -g mode-keys vi
setw -g xterm-keys on
set -g default-terminal "xterm-256color"
set -g history-limit 10000
#set -as terminal-features ",gnome*:RGB"
set -g terminal-overrides 'xterm*:smcup@:rmcup@' 


########################################
# PREFIX
########################################

# 기존 프리픽스(C-b, C-a 등) 해제
unbind C-b
set -g prefix C-q
bind  q send-prefix
bind-key C-q last-window


########################################
# MOUSE
########################################

unbind m
bind-key m if-shell 'tmux showw -gv mouse|grep on' \
         'set -g mouse off ; display "Mouse: OFF"' \
         'set -g mouse on  ; display "Mouse: ON"' \
         ;


########################################
# PANE
########################################

bind-key s set-window-option synchronize-panes 

bind-key -n C-tab selectp -l

bind-key h selectp -L
bind-key j selectp -D
bind-key k selectp -U
bind-key l selectp -R


########################################
# Windows
########################################

bind-key Space next
bind-key BSpace prev
bind-key tab last-window

# new window, split pane in same dir
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

########################################
# Other Binding
########################################

bind-key A  command-prompt "rename-window '%%'" 
bind r 'source-file ~/.config/tmux/tmux_base.conf; display "... Reload ~/.config/tmux/tmux_base.conf ..."'



########################################
# STATUS BAR
########################################

set -g @B1 '#[default]#[fg=green][#[default]'
set -g @B2 '#[default]#[fg=green]]#[default]'
#set -g base-index 1

# Toggle status bar
#bind s set -g status; bind C-s set -g status

# Default colors
set -g status-bg black; set -g status-fg white
#set-option -g status-fg colour24; set-option -g status-bg default
#set status-style fg=white,bg=black

# Left side of status bar
set -g status-left-length 80
set -g status-left '[M:#{?mouse,On,Off}]#{@B1}#[fg=blue]#H:#[fg=cyan]#S#{@B2} '

# Inactive windows in status bar
set-window-option -g window-status-format '#[fg=cyan]#I#[fg=blue]:#[fg=white]#W#[dim]#F'
# Current or active window in status bar
set-window-option -g window-status-current-format '#[bg=blue,bold]#[fg=cyan]#I#[fg=blue]:#[fg=white]#W#[dim]#F'

# Right side of status bar
set -g status-right-length 80
set -g status-right '[#{pane_current_path}]#{@B1}#T#{@B2}#{@B1}#[fg=blue]%Y-%m-%d #[default]%H:%M#{@B2}'
